after_script:
  - docker images

before_script:
  - IMAGE="postgres-plv8:$VERSION"

env:
  - VERSION=9.4-1.4
  - VERSION=9.4-1.5
  - VERSION=9.4-2
  - VERSION=9.5-1.4
  - VERSION=9.5-1.5
  - VERSION=9.5-2
  - VERSION=9.6-1.4
  - VERSION=9.6-1.5
  - VERSION=9.6-2
  - VERSION=10-2

language: bash

script:
  - docker build -t "${IMAGE}" "${VERSION}"
  - docker run -d --name postgres "${IMAGE}"
  - docker exec -it postgres pg_isready --timeout=60  -U postgres -h 127.0.0.1;
  - docker exec -it postgres psql -U postgres -c 'CREATE EXTENSION plv8; DO $$ plv8.elog(WARNING, plv8.version) $$ LANGUAGE plv8' | grep "${VERSION#????}"

services: docker
